version: 2.1
executors:
  node22:
    docker:
      - image: cimg/node:22.2.0
    working_directory: ~/repo

orbs:
  codecov: codecov/codecov@5.0.0
  fastly: adobe/fastly-cli@1.1.1

commands:
  setup:
    steps:
      - fastly/install:
          version: "10.2.2"

      - checkout
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm ci
      # - save_cache:
      #     paths:
      #     - node_modules
      #     key: v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
      - run:
          name: prepare test git user
          command: git config --global user.email "circleci@example.com" && git config --global user.name "CircleCi Build"

jobs:
  build:
    executor: node22

    steps:
      - setup
      - run: mkdir junit
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Run Build
          command: npm run fastly-build
      - codecov/upload
      - store_test_results:
          path: junit

      - store_artifacts:
          path: junit

  branch-deploy:
    executor: node22

    steps:
      - setup
      - run:
          name: revert changes to package-lock.json
          command: git checkout -- package-lock.json

      - run: npm ls @fastly/js-compute

      - run:
          name: Package and Branch Deployment
          command: HLX_FASTLY_AUTH=$HLX_FASTLY_CI_AUTH HLX_FASTLY_SVC=$HLX_FASTLY_CI_ID HLX_CLOUDFLARE_NAME=helix-rum-collector-ci npm run deploy

      - run:
          name: List Package Contents
          command: find bin && tar -tvf bin/dist/helix3/fastly-bundle.tar.gz

      - run:
          name: Wait for service to be updated
          command: sleep 45

      - run:
          name: Post-Deployment Integration Test
          command: npm run test-postdeploy
      - store_test_results:
          path: junit

  semantic-release:
    executor: node22

    steps:
      - setup
      - run:
          name: revert changes to package-lock.json
          command: git checkout -- package-lock.json

      - run:
          name: Semantic Release
          command: npm run semantic-release

workflows:
  default:
    jobs:
      - build:
          context: Project Helix
      - branch-deploy:
          context: Project Helix
          requires:
            - build
          filters:
            branches:
              ignore: main
      - semantic-release:
          context: Project Helix
          requires:
            - build
          filters:
            branches:
              only: main
