version: 2.1
executors:
  node:
    docker:
    - image: circleci/node:15-stretch
      environment:
        NPM_CONFIG_PREFIX: "~/.npm-global"
    working_directory: ~/repo

orbs:
  helix-post-deploy: adobe/helix-post-deploy@1.10.0
  fastly: adobe/fastly-cli@1.0.0

commands:
  setup:
    steps:
    - fastly/install

    - checkout
    # - restore_cache:
    #     keys:
    #     - v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
    - run:
        name: Installing Dependencies
        command: npm ci

    # - save_cache:
    #     paths:
    #     - node_modules
    #     key: v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
    - run:
        name: prepare test git user
        command: git config --global user.email "circleci@example.com" && git config --global user.name "CircleCi Build"

jobs:
  build:
    executor: node

    steps:
    - setup
    - run: mkdir junit
    # - run:
    #     name: Lint
    #     command: npm run lint

    - run:
        name: Run Tests
        command: npm run astest

    # - store_test_results:
    #     path: junit

    # - store_artifacts:
    #     path: junit

workflows:
  version: 2
  build:
    jobs:
    - build
#    - branch-deploy:
#        requires:
#          - build
#        filters:
#          branches:
#            ignore: main
#    - semantic-release:
#        requires:
#        - build
#        filters:
#          branches:
#            only: main
