version: 2.1
executors:
  node18:
    docker:
      - image: cimg/node:18.17
    working_directory: ~/repo

orbs:
  fastly: adobe/fastly-cli@1.1.1

commands:
  setup:
    steps:
      - fastly/install:
          version: "10.2.2"

      - checkout
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm ci

      # - save_cache:
      #     paths:
      #     - node_modules
      #     key: v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
      - run:
          name: prepare test git user
          command: git config --global user.email "circleci@example.com" && git config --global user.name "CircleCi Build"

jobs:
  build:
    executor: node18

    steps:
      - setup
      - run: mkdir junit
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Run Build
          command: npm run fastly-build

      - store_test_results:
          path: junit

      - store_artifacts:
          path: junit

  branch-deploy:
    executor: node18

    steps:
      - setup
      - run:
          name: revert changes to package-lock.json
          command: git checkout -- package-lock.json
      - run:
          name: Package
          command: npm run fastly-build

      - run:
          name: List Package Contents
          command: tar -tvf pkg/helix3.tar.gz

      - run:
          name: Branch Deployment
          command: fastly compute deploy -t $HLX_FASTLY_CI_AUTH -s $HLX_FASTLY_CI_ID

      - run:
          name: Wait for service to be updated
          command: sleep 60

      - run:
          name: Post-Deployment Integration Test
          command: npm run test-postdeploy
      - store_test_results:
          path: junit

  semantic-release:
    executor: node18

    steps:
      - setup
      - run:
          name: revert changes to package-lock.json
          command: git checkout -- package-lock.json

      - run:
          name: Semantic Release
          command: npm run semantic-release

workflows:
  default:
    jobs:
      - build
      - branch-deploy:
          requires:
            - build
          filters:
            branches:
              ignore: main
      - semantic-release:
          context: Project Helix
          requires:
            - build
          filters:
            branches:
              only: main
