name: build
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Tests
      run: npm run test
    - name: Fastly Build
      run: npm run fastly-build
    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v4
      with:
        coverage-files: lcov.info
        # minimum-coverage: 85
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        update-comment: true
    - name: List files
      run: find . -type f

    # Deploy to CI workers
    - name: Fastly Build
      run: npm run fastly-build
    - name: Fastly Version
      run: npm ls @fastly/js-compute
    - name: Package and Branch Deployment
      env:
        HLX_FASTLY_CI_ID: ${{ secrets.HLX_FASTLY_CI_ID }}
        HLX_FASTLY_CI_AUTH: ${{ secrets.HLX_FASTLY_CI_AUTH }}
        HLX_FASTLY_SVC: ${{ secrets.HLX_FASTLY_SVC }}
        HLX_CLOUDFLARE_EMAIL: ${{ secrets.HLX_CLOUDFLARE_EMAIL }}
        HLX_CLOUDFLARE_ACCOUNT: ${{ secrets.HLX_CLOUDFLARE_ACCOUNT }}
        HLX_CLOUDFLARE_AUTH: ${{ secrets.HLX_CLOUDFLARE_AUTH }}
        HLX_CLOUDFLARE_NAME: ${{ secrets.HLX_CLOUDFLARE_NAME }}
        BLAHBLAH: ${{ secrets.BLAHBLAH }}
      run: HLX_FASTLY_AUTH=$HLX_FASTLY_CI_AUTH HLX_FASTLY_SVC=$HLX_FASTLY_CI_ID HLX_CLOUDFLARE_NAME=helix-rum-collector-ci npm run deploy

