name: Semantic Release
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  semantic_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install
      run: npm ci
    - name: Semantic Release
      run: npm run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.ADOBE_BOT_GITHUB_TOKEN }}
        CORALOGIX_TAGGER_API_KEY: ${{ secrets.CORALOGIX_TAGGER_API_KEY }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        # Deployment variables
        HLX_FASTLY_AUTH: ${{ secrets.HLX_FASTLY_AUTH }}
        HLX_FASTLY_SVC: ${{ secrets.HLX_FASTLY_SERVICE_ID }}
        HLX_CLOUDFLARE_EMAIL: ${{ secrets.HLX_CLOUDFLARE_EMAIL }}
        HLX_CLOUDFLARE_ACCOUNT: ${{ secrets.HLX_CLOUDFLARE_ACCOUNT }}
        HLX_CLOUDFLARE_AUTH: ${{ secrets.HLX_CLOUDFLARE_AUTH }}
        IAB_SPIDER_LIST: ${{ secrets.IAB_SPIDER_LIST }}
